@startuml

title Class Diagram

class Game{
game: GameController()
}


class Cup{
die1: Die
die2 : Die
guiController: GuiController
+getSum():int
}

class Die {
-resultRoll: int

+roll(): random int
+toString(): String
}

class GameController {
guiController: GuiController
-playerCount : int
-player[playerCount]: Players[]
-board : BoardInit
-cup: Cup
+balance: int
square: Square[]
guiPlayers: GUI_Player[]

+run(): void
+init(): void

}

class LandOnSquare {
+landOnDeedSquare()
+landOnStartSquare()
+landOnJailSquare()
+landOnParkingSquare()
}

class Player{
-PlayerAccount : Account
-playerName: String
-squareIndex: int
+Player()
+withdrawMoney(): void
+depositMoney(): int
+getCurrentBalance(): int
+getPlayerName(): String
+UpdatePosision(): int
+getPosision(): int
+toString(): String

}

class Account{
-balance: int
+updateBalance()

}

class Square {
-pointsValue[]: int
-description[]: String

}

class BoardInit {
+deedName : Deed()

}

abstract class Square {
- name : String
}

class DeedSquare {
deed: Deed()
deedSold: boolean false
+hasDeed():boolean
+sellDeed():void

}

class Deed {
ownerName: Player
price: int

}

class Player {
name: String
addDeed(Deed s)

}

class Account {
-balance: int
+Account()
+withdraw(): void
+deposit(): void
+getBalance(): int

}

class ChanceSquare {}

class ChanceCard {}

class JailSquare {}

class StartSquare {}

class ParkingSquare {}

class GuiController{
-gui: GUI
-fields[24]: GUI_Fields
-gui_players[]: GUI_Player
-ownable: GUI_Ownable
+GuiController()
showMessage(): String
addPlayerOnBoard(): GUI_Player
move(): void
displayOwnerName(): void
updateBalance(): void
receiveRent(): void
getUserIntiger(): int
getUserString(): String
setDice(): void
winner(): String
}

GameController -up- Game

GuiController -right Game

GameController <-down- LandOnSquare

GuiController -left GameController

LandOnSquare <-down- BoardInit

LandOnSquare <-right- Player

BoardInit <|-down- Square

Square <|-down- DeedSquare

DeedSquare <-down- Deed

Square  <|-down- ChanceSquare

ChanceSquare <-down- ChanceCard

Square  <|-down- JailSquare

Square  <|-down- StartSquare

Square  <|-down- ParkingSquare


GameController <-right- Player

GameController "1" -left- "1" Cup




Cup "1" -down- "2" Die

Player "1" -down- "1" Account

@enduml


