@startuml

title Class Diagram
package "Controllers"{
class BuildController{
}
class GameController{
}

class GuiController{}
class SellController{}
}

package "GameComponent"{
package "Board"{
class Square {
-pointsValue[]: int
-description[]: String

}

class BoardInit {
+deedName : Deed()

}

abstract class Square {
- name : String
}

abstract class DeedSquare {
deed: Deed()
deedSold: boolean false
+hasDeed():boolean
+sellDeed():void

}

class DeedSquare_Buildable {

}

class DeedSquare_NonBuildable {}

abstract class Deed {
ownerName: Player
price: int

}

class Deed_Buildable{}

class Deed_NonBuildable{}
class ChanceSquare {}

class ChanceCard {}

class JailSquare {}

class StartSquare {}

class ParkingSquare {}
class TaxSquare{}
}

class Cup{
die1: Die
die2 : Die
guiController: GuiController
+getSum():int
}

class Die {
-resultRoll: int

+roll(): random int
+toString(): String
}

class Player{
-PlayerAccount : Account
-playerName: String
-squareIndex: int
+Player()
+withdrawMoney(): void
+depositMoney(): int
+getCurrentBalance(): int
+getPlayerName(): String
+UpdatePosision(): int
+getPosision(): int
+toString(): String

}

class Account{
-balance: int
+updateBalance()

}

}
package "Translator"{}
class Game{
game: GameController()
}





class GameController {
guiController: GuiController
-playerCount : int
-player[playerCount]: Players[]
-board : BoardInit
-cup: Cup
+balance: int
square: Square[]
guiPlayers: GUI_Player[]

+run(): void
+init(): void

}





class Player {
name: String
addDeed(Deed s)

}

class Account {
-balance: int
+Account()
+withdraw(): void
+deposit(): void
+getBalance(): int

}



class GuiController{
-gui: GUI
-fields[24]: GUI_Fields
-gui_players[]: GUI_Player
-ownable: GUI_Ownable
+GuiController()
showMessage(): String
addPlayerOnBoard(): GUI_Player
move(): void
displayOwnerName(): void
updateBalance(): void
receiveRent(): void
getUserInteger(): int
getUserString(): String
setDice(): void
winner(): String
}

class ChanceCard {
currentPlayer: Player

}

class MoveCard {

}

class Cardholder {}

class Bank {
}

Bank <-down- GameController

Bank <-down- Player

GameController -up- Game

GuiController -down- GameController

GameController <-down- BoardInit

BoardInit <|-down- Square

Square <|-down- DeedSquare

DeedSquare <|-down- DeedSquare_Buildable

DeedSquare <|-down- DeedSquare_NonBuildable

DeedSquare_Buildable <-down- Deed

DeedSquare_NonBuildable <-down- Deed


Deed <|-down- Deed_Buildable

Deed <|-down- Deed_NonBuildable

Square  <|-down- ChanceSquare

ChanceSquare <-down- ChanceCard

Square  <|-down- JailSquare

Square  <|-down- StartSquare

Square  <|-down- ParkingSquare

ChanceCard <|-down- MoveCard

ChanceCard <|-down- MoneyCard

ChanceCard <|-down- DeedCard

Player <-left- Cardholder

Cardholder <-down- Deed



GameController <-left- Player

GameController "1" -right- "1" Cup




Cup "1" -down- "2" Die

Player "1" -down- "1" Account

@enduml


